
# candidate_indices_creation = [
#     #CUSTMOER
#     "CREATE INDEX IDXa_CUSTOMER%s ON CUSTOMER%s(C_W_ID,C_D_ID,C_LAST,C_FIRST) USING HASH;",
#     "CREATE INDEX IDXb_CUSTOMER%s ON CUSTOMER%s(C_W_ID,C_D_ID,C_LAST) USING HASH;",
#     "CREATE INDEX IDXc_CUSTOMER%s ON CUSTOMER%s(C_W_ID,C_D_ID, C_ID) USING HASH;",
#     "CREATE INDEX IDXd_CUSTOMER%s ON CUSTOMER%s(C_W_ID,C_D_ID) USING HASH;",
#     "CREATE INDEX IDXe_CUSTOMER%s ON CUSTOMER%s(C_W_ID) USING HASH;",
#     "CREATE INDEX IDXf_CUSTOMER%s ON CUSTOMER%s(C_D_ID) USING HASH;",
#     #NEWORDER
#     "CREATE INDEX IDXa_NEWORDER%s ON NEW_ORDER%s (NO_D_ID,NO_W_ID, NO_O_ID) USING HASH;",
#     "CREATE INDEX IDXb_NEWORDER%s ON NEW_ORDER%s (NO_D_ID,NO_W_ID) USING HASH;",
#     "CREATE INDEX IDXc_NEWORDER%s ON NEW_ORDER%s (NO_D_ID) USING HASH;",
#     #OORDER
#     "CREATE INDEX IDXa_ORDER%s ON OORDER%s (O_W_ID,O_D_ID,O_C_ID,O_ID) USING HASH;",
#     "CREATE INDEX IDXb_ORDER%s ON OORDER%s (O_W_ID,O_D_ID,O_ID) USING HASH;",
#     "CREATE INDEX IDXc_ORDER%s ON OORDER%s (O_W_ID,O_D_ID) USING HASH;",
#     #ORDER_LINE
#     "CREATE INDEX IDXa_ORDER_LINE%s ON ORDER_LINE%s (OL_O_ID, OL_D_ID, OL_W_ID) USING HASH;",
#     "CREATE INDEX IDXb_ORDER_LINE%s ON ORDER_LINE%s (OL_NUMBER, OL_QUANTITY) USING HASH;",
#     #STOCK
#     "CREATE INDEX IDXa_STOCK%s ON STOCK%s(S_W_ID,S_I_ID,S_YTD) USING HASH;",
# ]

candidate_indices_creation = [
    # CUSTMOER
    "CREATE INDEX IDXa_CUSTOMER%s ON CUSTOMER%s(C_W_ID,C_D_ID,C_LAST,C_FIRST) USING BTREE;",
    "CREATE INDEX IDXb_CUSTOMER%s ON CUSTOMER%s(C_W_ID,C_D_ID,C_LAST) USING BTREE;",
    "CREATE INDEX IDXc_CUSTOMER%s ON CUSTOMER%s(C_W_ID,C_D_ID,C_ID) USING BTREE;",
    "CREATE INDEX IDXd_CUSTOMER%s ON CUSTOMER%s(C_W_ID,C_D_ID) USING BTREE;",
    "CREATE INDEX IDXe_CUSTOMER%s ON CUSTOMER%s(C_W_ID) USING BTREE;",
    "CREATE INDEX IDXf_CUSTOMER%s ON CUSTOMER%s(C_D_ID) USING BTREE;",
    # NEWORDER
    "CREATE INDEX IDXa_NEWORDER%s ON NEW_ORDER%s (NO_D_ID,NO_W_ID, NO_O_ID) USING BTREE;",
    "CREATE INDEX IDXb_NEWORDER%s ON NEW_ORDER%s (NO_D_ID,NO_W_ID) USING BTREE;",
    "CREATE INDEX IDXc_NEWORDER%s ON NEW_ORDER%s (NO_D_ID) USING BTREE;",
    # OORDER
    "CREATE INDEX IDXa_ORDER%s ON OORDER%s (O_W_ID,O_D_ID,O_C_ID,O_ID) USING BTREE;",
    "CREATE INDEX IDXb_ORDER%s ON OORDER%s (O_W_ID,O_D_ID,O_ID) USING BTREE;",
    "CREATE INDEX IDXc_ORDER%s ON OORDER%s (O_W_ID,O_D_ID) USING BTREE;",
    # ORDER_LINE
    "CREATE INDEX IDXa_ORDER_LINE%s ON ORDER_LINE%s (OL_O_ID, OL_D_ID, OL_W_ID) USING BTREE;",
    "CREATE INDEX IDXb_ORDER_LINE%s ON ORDER_LINE%s (OL_NUMBER, OL_QUANTITY) USING BTREE;",
    # STOCK
    "CREATE INDEX IDXa_STOCK%s ON STOCK%s(S_W_ID,S_I_ID,S_YTD) USING BTREE;"
]

candidate_indices_drop = [
    # CUSTMOER
    "ALTER TABLE CUSTOMER%s drop index IDXa_CUSTOMER%s;",
    "ALTER TABLE CUSTOMER%s drop index IDXb_CUSTOMER%s;",
    "ALTER TABLE CUSTOMER%s drop index IDXc_CUSTOMER%s;",
    "ALTER TABLE CUSTOMER%s drop index IDXd_CUSTOMER%s;",
    "ALTER TABLE CUSTOMER%s drop index IDXe_CUSTOMER%s;",
    "ALTER TABLE CUSTOMER%s drop index IDXf_CUSTOMER%s;",
    # NEWORDER
    "ALTER TABLE NEW_ORDER%s drop index IDXa_NEWORDER%s;",
    "ALTER TABLE NEW_ORDER%s drop index IDXb_NEWORDER%s;",
    "ALTER TABLE NEW_ORDER%s drop index IDXc_NEWORDER%s;",
    # OORDER
    "ALTER TABLE OORDER%s drop index IDXa_ORDER%s;",
    "ALTER TABLE OORDER%s drop index IDXb_ORDER%s;",
    "ALTER TABLE OORDER%s drop index IDXc_ORDER%s;",
    # ORDER_LINE
    "ALTER TABLE ORDER_LINE%s drop index IDXa_ORDER_LINE%s;",
    "ALTER TABLE ORDER_LINE%s drop index IDXb_ORDER_LINE%s;",
    # STOCK
    "ALTER TABLE STOCK%s drop index IDXa_STOCK%s;"
]


