
# candidate_indices_creation = [
#     #CUSTMOER
#     "CREATE INDEX IDXa_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_LAST,C_FIRST) USING HASH;",
#     "CREATE INDEX IDXb_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_LAST) USING HASH;",
#     "CREATE INDEX IDXc_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID, C_ID) USING HASH;",
#     "CREATE INDEX IDXd_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID) USING HASH;",
#     "CREATE INDEX IDXe_CUSTOMER ON CUSTOMER(C_W_ID) USING HASH;",
#     "CREATE INDEX IDXf_CUSTOMER ON CUSTOMER(C_D_ID) USING HASH;",
#     #NEWORDER
#     "CREATE INDEX IDXa_NEWORDER ON NEW_ORDER (NO_D_ID,NO_W_ID, NO_O_ID) USING HASH;",
#     "CREATE INDEX IDXb_NEWORDER ON NEW_ORDER (NO_D_ID,NO_W_ID) USING HASH;",
#     "CREATE INDEX IDXc_NEWORDER ON NEW_ORDER (NO_D_ID) USING HASH;",
#     #OORDER
#     "CREATE INDEX IDXa_ORDER ON OORDER (O_W_ID,O_D_ID,O_C_ID,O_ID) USING HASH;",
#     "CREATE INDEX IDXb_ORDER ON OORDER (O_W_ID,O_D_ID,O_ID) USING HASH;",
#     "CREATE INDEX IDXc_ORDER ON OORDER (O_W_ID,O_D_ID) USING HASH;",
#     #ORDER_LINE
#     "CREATE INDEX IDXa_ORDER_LINE ON ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID) USING HASH;",
#     "CREATE INDEX IDXb_ORDER_LINE ON ORDER_LINE (OL_NUMBER, OL_QUANTITY) USING HASH;",
#     #STOCK
#     "CREATE INDEX IDXa_STOCK ON STOCK(S_W_ID,S_I_ID,S_YTD) USING HASH;",
# ]

candidate_indices_creation = [
    # CUSTMOER
    "CREATE INDEX IDXa_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_LAST,C_FIRST) USING BTREE;",
    "CREATE INDEX IDXb_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_LAST) USING BTREE;",
    "CREATE INDEX IDXc_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_ID) USING BTREE;",
    "CREATE INDEX IDXd_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID) USING BTREE;",
    "CREATE INDEX IDXe_CUSTOMER ON CUSTOMER(C_W_ID) USING BTREE;",
    "CREATE INDEX IDXf_CUSTOMER ON CUSTOMER(C_D_ID) USING BTREE;",
    # NEWORDER
    "CREATE INDEX IDXa_NEWORDER ON NEW_ORDER (NO_D_ID,NO_W_ID, NO_O_ID) USING BTREE;",
    "CREATE INDEX IDXb_NEWORDER ON NEW_ORDER (NO_D_ID,NO_W_ID) USING BTREE;",
    "CREATE INDEX IDXc_NEWORDER ON NEW_ORDER (NO_D_ID) USING BTREE;",
    # OORDER
    "CREATE INDEX IDXa_ORDER ON OORDER (O_W_ID,O_D_ID,O_C_ID,O_ID) USING BTREE;",
    "CREATE INDEX IDXb_ORDER ON OORDER (O_W_ID,O_D_ID,O_ID) USING BTREE;",
    "CREATE INDEX IDXc_ORDER ON OORDER (O_W_ID,O_D_ID) USING BTREE;",
    # ORDER_LINE
    "CREATE INDEX IDXa_ORDER_LINE ON ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID) USING BTREE;",
    "CREATE INDEX IDXb_ORDER_LINE ON ORDER_LINE (OL_NUMBER, OL_QUANTITY) USING BTREE;",
    # STOCK
    "CREATE INDEX IDXa_STOCK ON STOCK(S_W_ID,S_I_ID,S_YTD) USING BTREE;"
]

candidate_indices_drop = [
    # CUSTMOER
    "ALTER TABLE CUSTOMER drop index IDXa_CUSTOMER;",
    "ALTER TABLE CUSTOMER drop index IDXb_CUSTOMER;",
    "ALTER TABLE CUSTOMER drop index IDXc_CUSTOMER;",
    "ALTER TABLE CUSTOMER drop index IDXd_CUSTOMER;",
    "ALTER TABLE CUSTOMER drop index IDXe_CUSTOMER;",
    "ALTER TABLE CUSTOMER drop index IDXf_CUSTOMER;",
    # NEWORDER
    "ALTER TABLE NEW_ORDER drop index IDXa_NEWORDER;",
    "ALTER TABLE NEW_ORDER drop index IDXb_NEWORDER;",
    "ALTER TABLE NEW_ORDER drop index IDXc_NEWORDER;",
    # OORDER
    "ALTER TABLE OORDER drop index IDXa_ORDER;",
    "ALTER TABLE OORDER drop index IDXb_ORDER;",
    "ALTER TABLE OORDER drop index IDXc_ORDER;",
    # ORDER_LINE
    "ALTER TABLE ORDER_LINE drop index IDXa_ORDER_LINE;",
    "ALTER TABLE ORDER_LINE drop index IDXb_ORDER_LINE;",
    # STOCK
    "ALTER TABLE STOCK drop index IDXa_STOCK;"
]


