import re

candidate_indices_creation = [
    # CUSTMOER, indexable column [C_W_ID,C_D_ID,C_LAST,C_FIRST] and [C_W_ID,C_D_ID,C_ID]
    "CREATE INDEX IDXa_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_LAST,C_FIRST) USING BTREE;",
    "CREATE INDEX IDXb_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_LAST) USING BTREE;",
    "CREATE INDEX IDXc_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_ID) USING BTREE;",
    "CREATE INDEX IDXd_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID) USING BTREE;",
    "CREATE INDEX IDXe_CUSTOMER ON CUSTOMER(C_W_ID) USING BTREE;",
    "CREATE INDEX IDXf_CUSTOMER ON CUSTOMER(C_D_ID) USING BTREE;",
    #
    "CREATE INDEX IDXg_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_FIRST) USING BTREE;",
    "CREATE INDEX IDXh_CUSTOMER ON CUSTOMER(C_D_ID,C_LAST,C_FIRST) USING BTREE;",
    "CREATE INDEX IDXi_CUSTOMER ON CUSTOMER(C_W_ID,C_LAST,C_FIRST) USING BTREE;",
    # "CREATE INDEX IDXi_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID) USING BTREE;",
    "CREATE INDEX IDXj_CUSTOMER ON CUSTOMER(C_D_ID,C_LAST) USING BTREE;",
    "CREATE INDEX IDXk_CUSTOMER ON CUSTOMER(C_LAST,C_FIRST) USING BTREE;",
    "CREATE INDEX IDXl_CUSTOMER ON CUSTOMER(C_FIRST,C_W_ID) USING BTREE;",
    # "CREATE INDEX IDXi_CUSTOMER ON CUSTOMER(C_W_ID) USING BTREE;",
    # "CREATE INDEX IDXj_CUSTOMER ON CUSTOMER(C_D_ID) USING BTREE;",
    "CREATE INDEX IDXm_CUSTOMER ON CUSTOMER(C_LAST) USING BTREE;",
    "CREATE INDEX IDXn_CUSTOMER ON CUSTOMER(C_FIRST) USING BTREE;",
    #
    "CREATE INDEX IDXo_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_LAST,C_FIRST, C_ID) USING BTREE;",
    "CREATE INDEX IDXp_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_LAST,C_ID) USING BTREE;",
    "CREATE INDEX IDXq_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_FIRST,C_ID) USING BTREE;",
    "CREATE INDEX IDXr_CUSTOMER ON CUSTOMER(C_W_ID,C_LAST,C_FIRST,C_ID) USING BTREE;",
    "CREATE INDEX IDXs_CUSTOMER ON CUSTOMER(C_D_ID,C_LAST,C_FIRST,C_ID) USING BTREE;",
    #
    # "CREATE INDEX IDXt_CUSTOMER ON CUSTOMER(C_W_ID,C_D_ID,C_ID) USING BTREE;",
    "CREATE INDEX IDXu_CUSTOMER ON CUSTOMER(C_W_ID,C_LAST,C_ID) USING BTREE;",
    "CREATE INDEX IDXv_CUSTOMER ON CUSTOMER(C_W_ID,C_FIRST,C_ID) USING BTREE;",

    "CREATE INDEX IDXw_CUSTOMER ON CUSTOMER(C_D_ID,C_LAST,C_ID) USING BTREE;",
    "CREATE INDEX IDXx_CUSTOMER ON CUSTOMER(C_D_ID,C_FIRST,C_ID) USING BTREE;",
    "CREATE INDEX IDXy_CUSTOMER ON CUSTOMER(C_FIRST,C_LAST,C_ID) USING BTREE;",

    "CREATE INDEX IDXz_CUSTOMER ON CUSTOMER(C_W_ID,C_ID) USING BTREE;",
    "CREATE INDEX IDXaa_CUSTOMER ON CUSTOMER(C_D_ID,C_ID) USING BTREE;",
    "CREATE INDEX IDXab_CUSTOMER ON CUSTOMER(C_FIRST,C_ID) USING BTREE;",
    "CREATE INDEX IDXac_CUSTOMER ON CUSTOMER(C_LAST,C_ID) USING BTREE;",
    "CREATE INDEX IDXad_CUSTOMER ON CUSTOMER(C_ID) USING BTREE;",

    # NEWORDER, indexable columns NO_D_ID,NO_W_ID, NO_O_ID
    "CREATE INDEX IDXa_NEWORDER ON NEW_ORDER (NO_D_ID,NO_W_ID, NO_O_ID) USING BTREE;",
    "CREATE INDEX IDXb_NEWORDER ON NEW_ORDER (NO_D_ID,NO_W_ID) USING BTREE;",
    "CREATE INDEX IDXc_NEWORDER ON NEW_ORDER (NO_D_ID,NO_O_ID) USING BTREE;",
    "CREATE INDEX IDXd_NEWORDER ON NEW_ORDER (NO_W_ID,NO_O_ID) USING BTREE;",
    "CREATE INDEX IDXe_NEWORDER ON NEW_ORDER (NO_D_ID) USING BTREE;",
    "CREATE INDEX IDXf_NEWORDER ON NEW_ORDER (NO_W_ID) USING BTREE;",
    "CREATE INDEX IDXg_NEWORDER ON NEW_ORDER (NO_O_ID) USING BTREE;",
    # OORDER, indexable columns O_W_ID,O_D_ID,O_C_ID,O_ID
    "CREATE INDEX IDXa_ORDER ON ORDERS (O_W_ID,O_D_ID,O_C_ID,O_ID) USING BTREE;",
    "CREATE INDEX IDXb_ORDER ON ORDERS (O_W_ID,O_D_ID,O_ID) USING BTREE;",
    "CREATE INDEX IDXc_ORDER ON ORDERS (O_W_ID,O_D_ID) USING BTREE;",
    "CREATE INDEX IDXd_ORDER ON ORDERS (O_W_ID,O_D_ID,O_C_ID) USING BTREE;",
    "CREATE INDEX IDXe_ORDER ON ORDERS (O_ID,O_D_ID,O_C_ID) USING BTREE;",
    "CREATE INDEX IDXf_ORDER ON ORDERS (O_W_ID,O_ID,O_C_ID) USING BTREE;",
    # "CREATE INDEX IDXg_ORDER ON ORDERS (O_W_ID,O_D_ID) USING BTREE;",
    "CREATE INDEX IDXh_ORDER ON ORDERS (O_D_ID,O_C_ID) USING BTREE;",
    "CREATE INDEX IDXi_ORDER ON ORDERS (O_C_ID,O_ID) USING BTREE;",
    "CREATE INDEX IDXj_ORDER ON ORDERS (O_ID,O_W_ID) USING BTREE;",
    "CREATE INDEX IDXk_ORDER ON ORDERS (O_W_ID,O_C_ID) USING BTREE;",
    "CREATE INDEX IDXl_ORDER ON ORDERS (O_D_ID) USING BTREE;",
    "CREATE INDEX IDXm_ORDER ON ORDERS (O_ID) USING BTREE;",
    "CREATE INDEX IDXn_ORDER ON ORDERS (O_W_ID) USING BTREE;",
    "CREATE INDEX IDXo_ORDER ON ORDERS (O_C_ID) USING BTREE;",
    # ORDER_LINE, indexable columns [OL_O_ID, OL_D_ID, OL_W_ID], [OL_NUMBER, OL_QUANTITY]
    "CREATE INDEX IDXa_ORDER_LINE ON ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID) USING BTREE;",
    "CREATE INDEX IDXb_ORDER_LINE ON ORDER_LINE (OL_NUMBER, OL_QUANTITY) USING BTREE;",
    "CREATE INDEX IDXc_ORDER_LINE ON ORDER_LINE (OL_O_ID, OL_D_ID) USING BTREE;",
    "CREATE INDEX IDXd_ORDER_LINE ON ORDER_LINE (OL_O_ID, OL_W_ID) USING BTREE;",
    "CREATE INDEX IDXe_ORDER_LINE ON ORDER_LINE (OL_D_ID, OL_W_ID) USING BTREE;",
    "CREATE INDEX IDXf_ORDER_LINE ON ORDER_LINE (OL_D_ID) USING BTREE;",
    "CREATE INDEX IDXg_ORDER_LINE ON ORDER_LINE (OL_O_ID) USING BTREE;",
    "CREATE INDEX IDXh_ORDER_LINE ON ORDER_LINE (OL_W_ID) USING BTREE;",
    "CREATE INDEX IDXi_ORDER_LINE ON ORDER_LINE (OL_QUANTITY) USING BTREE;",
    "CREATE INDEX IDXj_ORDER_LINE ON ORDER_LINE (OL_NUMBER) USING BTREE;",
    "CREATE INDEX IDXk_ORDER_LINE ON ORDER_LINE (OL_O_ID, OL_D_ID, OL_W_ID, OL_NUMBER, OL_QUANTITY) USING BTREE;",
    # STOCK, indexable column [S_W_ID,S_I_ID,S_YTD, S_QUANTITY]
    "CREATE INDEX IDXa_STOCK ON STOCK(S_W_ID,S_I_ID,S_YTD) USING BTREE;",
    "CREATE INDEX IDXb_STOCK ON STOCK(S_W_ID,S_I_ID) USING BTREE;",
    "CREATE INDEX IDXc_STOCK ON STOCK(S_W_ID,S_YTD) USING BTREE;",
    "CREATE INDEX IDXd_STOCK ON STOCK(S_I_ID,S_YTD) USING BTREE;",
    "CREATE INDEX IDXe_STOCK ON STOCK(S_W_ID) USING BTREE;",
    "CREATE INDEX IDXf_STOCK ON STOCK(S_I_ID) USING BTREE;",
    "CREATE INDEX IDXg_STOCK ON STOCK(S_YTD) USING BTREE;",

    "CREATE INDEX IDXh_STOCK ON STOCK(S_W_ID,S_I_ID,S_YTD,S_QUANTITY) USING BTREE;",
    "CREATE INDEX IDXi_STOCK ON STOCK(S_W_ID,S_I_ID,S_QUANTITY) USING BTREE;",
    "CREATE INDEX IDXj_STOCK ON STOCK(S_QUANTITY) USING BTREE;",
]

regex = "CREATE INDEX (.*) ON (.*)\((.*)\) USING BTREE;"
for candidate_index in candidate_indices_creation:
    result = re.findall(regex, candidate_index)
    print(str(result[0]) + ",")